name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  BE-build-test-package:
    name: BE Build & Test & Package
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: measdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        run: mvn -B package --file pom.xml -Dquarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/measdb
        working-directory: backend

      - name: Upload resulting Build package
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: backend/target
  
  BE-docker-image-delivery:
    name: BE Docker Image Delivery
    runs-on: ubuntu-latest
    needs: BE-build-test-package

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          name: Package
          path: backend/target/

      - name: Generate image tag
        id: date
        run: echo "::set-output name=date::$(date +%Y%m%d-%H%M%S)"

      - name: Docker build
        run: docker build -t lukacetina/devops-frontend:$TAG_NAME -f backend/src/main/docker/Dockerfile.jvm ./backend
        env:
          TAG_NAME: CD-${{ steps.date.outputs.date }}

      - name: Retag to latest
        run: docker tag lukacetina/devops-frontend:$TAG_NAME lukacetina/devops-frontend:latest
        env:
          TAG_NAME: CD-${{ steps.date.outputs.date }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Docker push
        run: docker push lukacetina/devops-frontend:$TAG_NAME && docker push lukacetina/devops-frontend:latest
        env:
          TAG_NAME: CD-${{ steps.date.outputs.date }}

  BE-static-code-analysis:
    name: BE SonarQube Analysis
    runs-on: ubuntu-latest
    needs: [BE-build-test-package]
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: maven
  
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=CetinaLuka_DevOpsDelavnica_d85aa944-01ca-434e-9066-e9856bbbefda -Dsonar.projectName='DevOpsDelavnica'
        working-directory: backend/

  FE-build:
    name: FE Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
  
      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        
      - name: Build frontend
        run: npm run build --no-progress 2>&1 >/dev/null || true # Mutes ESlint warnings
        working-directory: frontend

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/build/
        
  FE-static-code-analysis:
      name: FE SonarCloud Analysis
      runs-on: ubuntu-latest
      needs: [FE-build]
    
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: SonarCloud Scan Frontend
          uses: SonarSource/sonarqube-scan-action@v6
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FE }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          with:
            projectBaseDir: frontend/
        - name: SonarCloud Quality Gate Frontend
          uses: SonarSource/sonarqube-quality-gate-action@v1
          timeout-minutes: 5
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FE }}
          
  #cypress:
  #  name: Functional Tests
  #  runs-on: ubuntu-latest
  #  needs: [BE-deploy-on-azure, FE-deploy]
  #  strategy:
  #    fail-fast: false # https://github.com/cypress-io/github-action/issues/48
  #    matrix:
  #      containers: [ 1, 2 ] # Uses 2 parallel instances

  #  services:
  #    postgres:
  #      image: postgres:16
  #      env:
  #        POSTGRES_DB: measdb
  #        POSTGRES_USER: postgres
  #        POSTGRES_PASSWORD: postgres
  #      options: >-
  #        --health-cmd pg_isready
  #        --health-interval 10s
  #        --health-timeout 5s
  #        --health-retries 5
  #      ports:
  #        - 5432:5432
          
  #  steps:
  #    - name: Checkout repository
  #      uses: actions/checkout@v3

  #    - name: Setup Java
  #      uses: actions/setup-java@v3
  #      with:
  #          distribution: 'adopt'
  #          java-version: '21'
  #          cache: maven
  #          
  #    - name: Start backend
  #      run: |
  #       ./mvnw quarkus:dev &
  #      working-directory: backend

  #    - name: Wait for Quarkus Server to be Ready
  #      run: |
  #       echo "Waiting for Quarkus server to start..."
  #       until curl --output /dev/null --head http://localhost:8280/api/v1/history; do
  #        printf '.'
  #        sleep 5
  #      done
  #      echo "Quarkus server is up and running!"

  #    - name: Ouput backend endpoint
  #      run: |
  #       curl http://localhost:8280/api/v1/history

  #    - name: Setup Node.js
  #      uses: actions/setup-node@v3
  #      with:
  #        node-version: 18
  #        cache: 'npm'
  #        cache-dependency-path: frontend/package-lock.json
  # 
  #    - name: Install dependencies
  #      run: npm ci
  #      working-directory: frontend
  #      
  #    - name: Start frontend
  #      run: npm run start &
  #      working-directory: frontend
  #
  #    - name: Wait for React Server to be Ready
  #      run: |
  #           echo "Waiting for React server to start..."
  #           until curl --output /dev/null --head http://localhost:3000; do
  #            printf '.'
  #            sleep 5
  #           done
  #           echo "React server is up and running!"

  #    - name: Cypress run
  #        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
  #      uses: cypress-io/github-action@v6
  #      with:
  #        # Starts web server for E2E tests
  #        # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
  #        
  #        wait-on: 'http://localhost:3000'
  #        record: true
  #        parallel: true
  #      env:
  #        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #        # you can also add a GitHub secret

 
